# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:15
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test:ci
      - run:
          name: Build package
          command: yarn build
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:15
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org:_authToken=$NPM_AUTH_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  package:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
